# Generated by Django 5.0 on 2025-12-05 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chapitre',
                'verbose_name_plural': 'Chapitres',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('level', models.CharField(choices=[('PREMIERE', 'Première'), ('TERMINALE', 'Terminale')], max_length=10, verbose_name='Niveau')),
                ('description', models.TextField(verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TEXT', 'Texte'), ('CODE_SAMPLE', 'Exemple de code'), ('EXERCISE', 'Exercice'), ('QUIZ', 'Quiz'), ('VIDEO', 'Vidéo')], max_length=20, verbose_name='Type')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('content_markdown', models.TextField(verbose_name='Contenu (Markdown)')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='courses.chapter')),
            ],
            options={
                'verbose_name': 'Bloc de contenu',
                'verbose_name_plural': 'Blocs de contenu',
                'ordering': ['chapter', 'order'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course'),
        ),
        migrations.CreateModel(
            name='ChapterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Date limite')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.chapter')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_assignments', to='accounts.classroom')),
            ],
            options={
                'verbose_name': 'Attribution de chapitre',
                'verbose_name_plural': 'Attributions de chapitres',
                'ordering': ['-assigned_at'],
                'unique_together': {('classroom', 'chapter')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('course', 'slug')},
        ),
    ]
