# Generated by Django 5.0 on 2025-12-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_seconde_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('SNT', 'SNT (Seconde)'), ('PREMIERE', 'NSI Première'), ('TERMINALE', 'NSI Terminale')], max_length=10, verbose_name='Niveau'),
        ),
    ]
