# Generated by Django 5.0 on 2025-12-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_seconde_to_snt'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.CharField(default='📚', max_length=10, verbose_name='Icône'),
        ),
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="URL de l'image"),
        ),
    ]
