# Generated by Django 5.0 on 2025-12-05 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('type', models.CharField(choices=[('PYTHON', 'Python'), ('SQL', 'SQL'), ('MCQ', 'QCM'), ('PARSONS', 'Parsons (réorganisation)')], max_length=10, verbose_name='Type')),
                ('statement_markdown', models.TextField(verbose_name='Énoncé (Markdown)')),
                ('starter_code', models.TextField(blank=True, verbose_name='Code de départ')),
                ('tests_definition', models.JSONField(default=dict, help_text='Pour Python: liste de tests. Pour SQL: schéma et requêtes. Pour MCQ: questions et réponses.', verbose_name='Définition des tests (JSON)')),
                ('xp_reward', models.IntegerField(default=10, verbose_name='XP récompensé')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.chapter')),
            ],
            options={
                'verbose_name': 'Exercice',
                'verbose_name_plural': 'Exercices',
                'ordering': ['chapter', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name="Contenu de l'indice")),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('xp_cost', models.IntegerField(default=0, help_text="XP déduits si l'élève utilise cet indice", verbose_name='Coût en XP')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='exercises.exercise')),
            ],
            options={
                'verbose_name': 'Indice',
                'verbose_name_plural': 'Indices',
                'ordering': ['exercise', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=False, verbose_name='Réussi')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('attempt_data', models.JSONField(default=dict, help_text='Code soumis, réponses, temps passé, etc.', verbose_name='Données de la tentative')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exercises.exercise')),
            ],
            options={
                'verbose_name': 'Tentative',
                'verbose_name_plural': 'Tentatives',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'exercise', 'passed'], name='exercises_a_user_id_fa8de9_idx')],
            },
        ),
        migrations.CreateModel(
            name='HintUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('hint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='exercises.hint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Utilisation d'indice",
                'verbose_name_plural': "Utilisations d'indices",
                'ordering': ['-used_at'],
                'unique_together': {('user', 'hint')},
            },
        ),
    ]
