# Generated by Django 5.0 on 2025-12-06 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0004_rename_seconde_to_snt'),
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('type', models.CharField(choices=[('DIAGNOSTIC', 'Test de positionnement'), ('CHECKPOINT', 'Checkpoint'), ('FINAL', 'Évaluation finale')], max_length=20, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='Durée (minutes)')),
                ('passing_score', models.IntegerField(default=50, verbose_name='Score minimum (%)')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.course', verbose_name='Cours associé')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=1, verbose_name='Points')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exercises.assessment')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise', verbose_name='Exercice')),
            ],
            options={
                'verbose_name': "Question d'évaluation",
                'verbose_name_plural': "Questions d'évaluation",
                'ordering': ['assessment', 'order'],
                'unique_together': {('assessment', 'exercise')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Score (%)')),
                ('points_earned', models.IntegerField(verbose_name='Points obtenus')),
                ('points_total', models.IntegerField(verbose_name='Points total')),
                ('time_spent_minutes', models.IntegerField(blank=True, null=True, verbose_name='Temps passé (minutes)')),
                ('started_at', models.DateTimeField(verbose_name='Commencé le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exercises.assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Résultat d'évaluation",
                'verbose_name_plural': "Résultats d'évaluation",
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'assessment')},
            },
        ),
        migrations.CreateModel(
            name='ClassroomAssessmentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.FloatField(verbose_name='Moyenne de la classe')),
                ('median_score', models.FloatField(verbose_name='Médiane')),
                ('min_score', models.IntegerField(verbose_name='Score minimum')),
                ('max_score', models.IntegerField(verbose_name='Score maximum')),
                ('completion_rate', models.FloatField(verbose_name='Taux de complétion (%)')),
                ('students_passed', models.IntegerField(verbose_name='Élèves ayant réussi')),
                ('students_total', models.IntegerField(verbose_name='Total élèves')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_stats', to='exercises.assessment')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_stats', to='accounts.classroom')),
            ],
            options={
                'verbose_name': 'Statistiques classe',
                'verbose_name_plural': 'Statistiques des classes',
                'unique_together': {('classroom', 'assessment')},
            },
        ),
    ]
